project:
  type: website

website:
  title: "personal-website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: Bio
      - href: gallery.qmd
        text: Gallery
      - href: blogs.qmd
        text: Blog
      - href: paint.qmd
        text: Artwork
      - href: photos.qmd
        text: Photography
  
  page-footer: 
    right: "&copy; 2024, Yuge Song"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute: 
  freeze: auto

