project:
  type: website

website:
  title: "YUGE SONG"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects & Publications
      - href: artwork.qmd
        text: Artwork
      - href: photography.qmd
        text: Photography
  
  page-footer: 
    right: "&copy; 2024, Yuge Song"


format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

execute: 
  freeze: auto

